stages:
  - test

services:
  - docker:19.03.12

test:
  stage: test
  script:
    - docker-compose -f docker-compose.yml build
    - docker-compose -f docker-compose.yml up -d db
    - docker-compose -f docker-compose.yml up -d studybuddy.api
    - docker-compose -f docker-compose.yml run studybuddy.api.tests
